<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <!-- Version Variables -->
  <PropertyGroup>
    <DotNetVersion>10.0.11</DotNetVersion>
    <ScalarVersion>2.17.1</ScalarVersion>
    <TUnitVersion>1.65.0</TUnitVersion>
  </PropertyGroup>

  <!-- Production Dependencies -->
  <ItemGroup Label="Production">
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="$(DotNetVersion)" />
    <PackageVersion Include="Scalar.AspNetCore" Version="$(ScalarVersion)" />
  </ItemGroup>

  <!-- Testing Dependencies -->
  <ItemGroup Label="Testing">
    <PackageVersion Include="TUnit" Version="$(TUnitVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
  </ItemGroup>

</Project>
